"""Prompt templates for LLM models."""

from .judge_prompts import JUDGE_PROMPT
from .query_prompts import (
    QUERY_REWRITE_PROMPT,
    QUERY_EXTEND_PROMPT,
    QUERY_EXTEND_ENGLISH_PROMPT
)
from .generation_prompts import (
    QUERY_GENERATION_DATASET_PROMPT,
    QUERY_GENERATION_DATASET_2_PROMPT
)

__all__ = [
    "JUDGE_PROMPT",
    "QUERY_REWRITE_PROMPT",
    "QUERY_EXTEND_PROMPT",
    "QUERY_EXTEND_ENGLISH_PROMPT",
    "QUERY_GENERATION_DATASET_PROMPT",
    "QUERY_GENERATION_DATASET_2_PROMPT",
]
