"""Prompt templates for query processing tasks."""

QUERY_REWRITE_PROMPT = """
Your task is to rewrite user query from Portuguese to English.
Rewrite might be a bit longer, most important criteria is that it captures all the information from the original

User query:
{query}

{{
    "thoughts": string, // 1-2 sentence for thoughts
    "query": string, // user query in english
}}
"""

QUERY_EXTEND_PROMPT = """
Your task is to rewrite user search query for food/groceries delivery service.
User puts simple query, and you need to come up with possible product names/titles and category.

Possible categories (not extensive list):
SAUDE_E_BEM_ESTAR MEDICAMENTOS ALOPATICOS
ALIMENTOS_PREPARADOS SANDUICHES HAMBURGUERES
OUTROS OUTROS OUTROS
ALIMENTOS_PREPARADOS PRATOS OUTROS
ALIMENTOS_PREPARADOS SORVETES_ACAIS_FRUTAS SORVETES
BEBIDAS REFRIGERANTES REFRIGERANTE_COLA
BOMBONIERE CHOCOLATES BARRAS
BEBIDAS SUCOS_VITAMINAS_SMOOTHIES SUCOS_VITAMINAS_SMOOTHIES
ALIMENTOS_PREPARADOS PRATOS CORTES_DE_AVES
ALIMENTOS_PREPARADOS BOLOS_TORTAS_FONDUES BOLOS
ALIMENTOS_PREPARADOS PRATOS SUSHIS_SASHIMIS_TEMAKIS
ALIMENTOS_PREPARADOS PIZZAS PIZZAS
CASA_DECORACAO LIMPEZA_CASA PRODUTOS_LIMPEZA_CASA
MERCEARIA BISCOITOS_SNACKS BISCOITOS
ALIMENTOS_PREPARADOS OUTROS OUTROS
ALIMENTOS_PREPARADOS PRATOS CORTES_BOVINOS
ALIMENTOS_PREPARADOS SORVETES_ACAIS_FRUTAS ACAIS
ALIMENTOS_PREPARADOS PRATOS BATATAS_PREPARADAS
ALIMENTOS_PREPARADOS SALGADINHOS_APERITIVOS PASTEIS
BELEZA_ESTETICA_HIGIENE_PESSOAL HIGIENE_PESSOAL SABONETES
BELEZA_ESTETICA_HIGIENE_PESSOAL HIGIENE_PESSOAL DESODORANTE
MERCEARIA BISCOITOS_SNACKS SNACKS
BEBIDAS REFRIGERANTES REFRIGERANTE_GUARANA
BEBIDAS CERVEJAS CERVEJAS_TRADICIONAIS
BEBIDAS AGUAS_AGUAS_DE_COCO AGUA_SEM_GAS
SAUDE_E_BEM_ESTAR SUPLEMENTOS_VITAMINAS SUPLEMENTOS
ALIMENTOS_PREPARADOS SANDUICHES HOT_DOGS
PET RACAO_ALIMENTACAO ALIMENTACAO_CAES
ALIMENTOS_PREPARADOS SALGADINHOS_APERITIVOS OUTROS
BEBE TROCA_DE_FRALDAS FRALDAS_INFANTIS
BELEZA_ESTETICA_HIGIENE_PESSOAL HIGIENE_INTIMA ABSORVENTE_EXTERNO
MERCEARIA MASSAS_SECAS MASSA_MACARRAO
ALIMENTOS_PREPARADOS PRATOS PEIXES_FRUTOS_DO_MAR
ALIMENTOS_PREPARADOS PRATOS MASSAS
PET RACAO_ALIMENTACAO ALIMENTACAO_GATOS
MERCEARIA OUTROS OUTROS
ALIMENTOS_PREPARADOS PRATOS PARMEGIANAS
BELEZA_ESTETICA_HIGIENE_PESSOAL HIGIENE_BUCAL CREME_GEL_DENTAL
CASA_DECORACAO LAVANDERIA SABAO_EM_PO
BOMBONIERE CHOCOLATES OVOS_DE_PASCOA
BELEZA_ESTETICA_HIGIENE_PESSOAL CUIDADOS_CABELO SHAMPOO
BEBIDAS ENERGETICO_ISOTONICO ENERGETICOS
BEBIDAS LEITES LEITE_TRADICIONAL
MERCEARIA ACOUGUE BOVINOS
FRIOS_LATICINIOS IOGURTES_E_FERMENTADOS COM_SABORES
MERCEARIA PAES PAO_DE_FORMA
BEBIDAS REFRIGERANTES REFRIGERANTE_LIMAO
BELEZA_ESTETICA_HIGIENE_PESSOAL CUIDADOS_PELE HIDRATANTE
ALIMENTOS_PREPARADOS PRATOS SALADAS
BEBIDAS REFRIGERANTES OUTROS
ALIMENTOS_PREPARADOS BOLOS_TORTAS_FONDUES TORTAS
BEBIDAS REFRIGERANTES REFRIGERANTE_SABORES
BEBIDAS VINHOS VINHOS_MESA_FINO_TINTO
BELEZA_ESTETICA_HIGIENE_PESSOAL CUIDADOS_CABELO KITS_DE_SHAMPOO_CONDICIONADOR
BELEZA_ESTETICA_HIGIENE_PESSOAL CUIDADOS_PELE DERMOCOSMETICOS
BOMBONIERE CHOCOLATES CAIXAS
ALIMENTOS_PREPARADOS SANDUICHES MISTOS_PAO_NA_CHAPA_SIMILARES
ALIMENTOS_PREPARADOS SOBREMESAS OUTROS
BELEZA_ESTETICA_HIGIENE_PESSOAL CUIDADOS_CABELO TONALIZANTES_COLORACAO_TINTURA
ALIMENTOS_PREPARADOS PRATOS CORTES_SUINOS
BOMBONIERE BALAS_GOMAS BALAS
ALIMENTOS_PREPARADOS PRATOS YAKISSOBA_LAMENS
BEBIDAS OUTROS OUTROS
CASA_DECORACAO LIMPEZA_CASA ACESSORIOS_LIMPEZA_CASA
MERCEARIA FARINACEOS_AMIDO FARINHA
ALIMENTOS_PREPARADOS PRATOS FEIJOADAS
ALIMENTOS_PREPARADOS SORVETES_ACAIS_FRUTAS MILK_SHAKES
ALIMENTOS_PREPARADOS PRATOS SOPAS_CALDOS_CREMES
FRIOS_LATICINIOS FRIOS LINGUICA
ALIMENTOS_PREPARADOS SALGADINHOS_APERITIVOS ESFIHAS
MERCEARIA CAFE_CHAS_ACHOCOLATADOS ACHOCOLATADO_EM_PO
CASA_DECORACAO LAVANDERIA AMACIANTE
BELEZA_ESTETICA_HIGIENE_PESSOAL HIGIENE_BUCAL ESCOVA_DENTAL
BELEZA_ESTETICA_HIGIENE_PESSOAL ESMALTERIA ESMALTES_BASES
BEBIDAS CAFES_CHAS CHA_PRONTO
CASA_DECORACAO LAVANDERIA SABAO_LIQUIDO
SAUDE_E_BEM_ESTAR PRIMEIROS_SOCORROS CURATIVOS
BEBIDAS REFRIGERANTES REFRIGERANTE_LARANJA
MERCEARIA GRAOS_CEREAIS ARROZ
FRIOS_LATICINIOS QUEIJOS QUEIJO_MOZZARELLA
BELEZA_ESTETICA_HIGIENE_PESSOAL CUIDADOS_CABELO HIDRATACAO_TRATAMENTO_CAPILAR
ALIMENTOS_PREPARADOS SALGADINHOS_APERITIVOS BOLINHOS_CROQUETES_RISOLES
ALIMENTOS_PREPARADOS BOLOS_TORTAS_FONDUES BROWNIES
BEBE NUTRICAO_INFANTIL FORMULA_INFANTIL
BOMBONIERE BALAS_GOMAS GOMAS_DE_MASCAR
ALIMENTOS_PREPARADOS SOBREMESAS COPOS_FELICIDADE
MERCEARIA ACOUGUE AVES
BELEZA_ESTETICA_HIGIENE_PESSOAL CUIDADOS_PELE PROTETOR_SOLAR
FLV FRUTAS OUTROS
MERCEARIA CAFE_CHAS_ACHOCOLATADOS CAFE_MOIDO
BEBIDAS CERVEJAS CERVEJAS_ESPECIAIS
BELEZA_ESTETICA_HIGIENE_PESSOAL HIGIENE_INTIMA PAPEL_HIGIENICO
MERCEARIA PAES PAO_DE_QUEIJO
SAUDE_E_BEM_ESTAR SAUDE_SEXUAL PRESERVATIVO
BELEZA_ESTETICA_HIGIENE_PESSOAL HIGIENE_BUCAL ENXAGUANTE_ANTISSEPTICO_BUCAL
BELEZA_ESTETICA_HIGIENE_PESSOAL CUIDADOS_CABELO FINALIZADORES_MODELADORES
FRIOS_LATICINIOS QUEIJOS QUEIJO_MINAS
ALIMENTOS_PREPARADOS SANDUICHES SANDUICHES_NATURAIS
ALIMENTOS_PREPARADOS PRATOS ESTROGONOFES
CASA_DECORACAO COZINHA EMBALAGENS_DESCARTAVEIS

User query:
{query}

Reply strickly in Portuguese. Predict the category (if no one fits come up with a new one in a similar format), and come up with 3 names/titles.

Reply in the following json format:
{{
    "category": string // category from the list above or new one in Portuguese
    "names": [string], // list of 3 string, possible diverse names in Portuguese
}}
"""

QUERY_EXTEND_ENGLISH_PROMPT = """
Your task is to rewrite user search query for food/groceries delivery service.
User puts simple query in Portuguese, and you need to come up with possible product names/titles.
Make name/titles a bit longer, adding descriptions.

User query:
{query}

Reply strickly in English.

Reply in the following json format:
{{
    "names": [string], // list of 3 string, possible diverse names in English
}}
"""
